[package]
name = "xtask"
version = "0.1.0"
edition.workspace = true
readme.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
bench = false
doc = false
doctest = false
name = "xtask"
path = "src/main.rs"
test = false

[dependencies]
anyhow = { version = "1.0.104", features = ["backtrace"] }
log = { version = "0.4.34", features = ["alloc"] }
owo-colors = { version = "4.4.0", features = ["supports-colors"] }
